### ISSUE TITLE
[BE] AWS EB 배포시 imp 모듈을 찾지 못하는 에러처리

### ISSUE THREAD

**Issue by Hyunminmax** [OZ-Coding-School/oz_02_collabo-003-BE#66]

**Comment by Hyunminmax** [comment]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Study\Projects\KluckDev\.venv\Scripts\eb.exe\__main__.py", line 4, in <module>
    from cement.core import foundation, handler, hook
  File "C:\Study\Projects\KluckDev\.venv\Lib\site-packages\cement\core\foundation.py", line 18, in <module>
    from imp import reload  # pragma: nocover
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'
```
위 문제를 해결하기 위해 검색한 방법으로는 

1. GPT 추천 방법
```
git clone https://github.com/datafolklabs/cement.git
cd cement
sed -i 's/from imp import reload/from importlib import reload/' cement/core/extension.py
```
진행을 해봤지만 변화가 없었고 cement/core/extension.py 파일을 찾아보니 위 내용이 애초에 존재하지 않음. 

2. poetry에 awsebcli와 cement의 설치 순서 변경
3. cement 2.8.2의 extension.py를 위 1번 방법과 같이 수정

위 방법 모두 영향이 없었고 python 인터프리터를 3.12에서 3.11로 변경하니 eb deploy가 동작은 하지만 
예전에는 본 적 없는 
```
C:\Study\Projects\KluckDev\.venv\Lib\site-packages\ebcli\display\screen.py:442: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(
C:\Study\Projects\KluckDev\.venv\Lib\site-packages\ebcli\controllers\create.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if instance_types is "":
Creating application version archive "app-012c-240529_145656710294".
Uploading: [##################################################] 100% Done...
2024-05-29 05:57:44    INFO    Environment update is starting.      
2024-05-29 05:57:49    ERROR   Failed to check health. Verify the permissions on the environment's service role and try again later. Permissions changes take up to two hours to propagate.
2024-05-29 05:57:49    ERROR   Failed to deploy application.
```
SyntaxWarninig과 공포의 2시간 오류가 발행하고 있다.

**Comment by Hyunminmax** [comment]
권한 문제는 지성님이 권한을 수정해준 방법으로 성공했으나. 
안내와는 다르게 변경된 권한의 적용에 2시간보다 더 많은 시간이 소요되는 것으로 결론.
